### ISSUE TITLE
Añadir una licencia libre

### ISSUE THREAD

**Issue by JJ** [transparenciagov2020/transparenciagov2020.github.io#1]
Por si alguien quiere tomar el manifiesto y adaptarlo. CC-by-sa es razonable.

**Comment by transparenciagov2020** [comment]
Excelente propuesta, gracias @JJ 

Licencia añadida en https://github.com/transparenciagov2020/transparenciagov2020.github.io/commit/fb2d20438cc7723d83e0df1c798e960796569d90
